name: Test and Lint
on: push
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: sudo docker-compose run --rm composer install
      - name: Test
        run: sudo docker-compose run --rm phpunit
      - name: Lint
        run: sudo docker-compose run --rm phpcs
